name: DOS CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo libisl-dev

      - name: Set up cross-compiler
        run: |
          export PREFIX="${HOME}/opt/cross"
          export TARGET=i686-elf
          export PATH="${PREFIX}/bin:${PATH}"
          mkdir -p ${HOME}/src
          cd ${HOME}/src
          wget -nc https://ftp.gnu.org/gnu/binutils/binutils-2.35.tar.xz
          tar -xf binutils-2.35.tar.xz
          wget -nc http://ftp.lip6.fr/pub/gcc/releases/gcc-10.2.0/gcc-10.2.0.tar.xz
          tar -xf gcc-10.2.0.tar.xz
          mkdir -p build-binutils build-gcc
          
      - name: Build binutils
        run: |
          export PREFIX="${HOME}/opt/cross"
          export TARGET=i686-elf
          export PATH="${PREFIX}/bin:${PATH}"
          cd ${HOME}/src/build-binutils
          ../binutils-2.35/configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
          make -j$(nproc)
          sudo make install

      - name: Build GCC
        run: |
          export PREFIX="${HOME}/opt/cross"
          export TARGET=i686-elf
          export PATH="${PREFIX}/bin:${PATH}"
          cd ${HOME}/src/build-gcc
          ../gcc-10.2.0/configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c,c++ --without-headers
          make all-gcc -j$(nproc)
          make all-target-libgcc -j$(nproc)
          sudo make install-gcc
          sudo make install-target-libgcc

      - name: Verifying
        run: |
          export PREFIX="${HOME}/opt/cross"
          export TARGET=i686-elf
          export PATH="${PREFIX}/bin:${PATH}"
          ${HOME}/opt/cross/bin/i686-elf-gcc --version

      - name: Build DOS
        run: |
          cd dos
          export PREFIX="${HOME}/opt/cross"
          export TARGET=i686-elf
          export PATH="${PREFIX}/bin:${PATH}"
          make
